on: ["push", "pull_request"]

name: Coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Use Python 3.8.6
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.6

    - name: pip install coveralls, pip install -r requirements.txt
      env: 
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        pip install coveralls
        pip install pytest
        pip install pytest-cov
        pip install -r requirements.txt
        pytest --cov-report term
        coveralls
