on: ["push", "pull_request"]

name: Coveralls

jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:

    - uses: actions/checkout@v1

    - name: Use Node.js 10.x
      uses: actions/setup-python@v1
      with:
        python-version: 3.8.2

    - name: pip install coveralls, pip install -r requirements.txt
      run: |
        pip install coveralls
        pip install -r requirements.txt

    - name: Coveralls
      uses: coverallsapp/github-action@master
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
