name: Coveralls
on: ["push", "pull_request"]

jobs:
  Build:
    name: Linux Coverage test
    runs-on: ubuntu-latest
    
    steps:
      - name: Setup Python
        uses: actions/setup-python@v2

      - name: Run coverage commands
        run: |
           pip install --upgrade pip
           python -m pip install coveralls
           coverage run --source=Creeper -m pytest src/
           coveralls
